source 'https://ruby.taobao.org'

gem 'rails'
gem 'mysql2'
gem 'sass-rails', '~> 5.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.1.0'
gem 'jquery-rails'
gem 'turbolinks'
gem 'jbuilder', '~> 2.0'
gem 'sdoc', '~> 0.4.0', group: :doc
gem 'bcrypt', '~> 3.1.7'

gem 'kaminari'
gem 'bootstrap-sass'
gem 'simple_form'
gem 'rails-i18n'
gem 'ransack'
gem 'httparty'

gem 'unicorn'
gem 'unicorn-worker-killer'

group :development, :test do
  gem 'byebug'

  gem 'factory_girl_rails'
  gem 'database_cleaner'
end

group :development do
  gem 'capistrano-rails'
  gem 'capistrano-rvm'
end
